services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_R2DBC_URL: r2dbc:pool:postgres://flux-pg.flux.local/flux
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres

      SPRING_LIQUIBASE_URL: jdbc:postgresql://flux-pg.flux.local/flux
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres

      HISTFILE: /app/.local/.bash_history
    networks:
      default:
        aliases:
          - flux-api.flux.local
    ports:
      - 3091:8080
    volumes:
      - ./:/app
      - gradle-home:/root/.gradle
    depends_on:
      - pg
    stdin_open: true
    tty: true

  pg:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: flux
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.local/volumes/pg/data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d flux
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - flux-pg.flux.local

volumes:
  gradle-home:

networks:
  default:
    name: flux-dev
